[tasks.build]
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static/public/pkg"]
watch = { ignore_pattern = "static/public/*" }

[tasks.serve]
command = "simple-http-server"
args = ["-i", "./static/public", "-p", "8080", "--nocache", "--try-file", "./static/public/index.html"]